### PR TITLE
remove lodash peer dep

### PR DESCRIPTION
**Pull request by Jephuff**

### CODE REVIEW

**Comment by shanewilson** [comment]
doesn't this make the final js bigger?

**Comment by Jephuff** [comment]
I suppose it would a tiny bit, but lodash 3 and lodash 4 are not compatible so this avoids having to support both.

**Comment by shanewilson** [comment]
icgc uses 3?

**Comment by Jephuff** [comment]
yep

**Comment by cheapsteak** [comment]
yep

**Pull request merged**
