### PR TITLE
:sparkles: use knitjs

### PR DESCRIPTION
**Pull request by shanewilson**
uses `knit` instead of `buildjs` which means `-lerna` and `+yarn`

```
❯ yarn knit -- list --dependencies
yarn knit v0.17.9
$ knit list --dependencies
 ✔ discovering modules
 ✔ reading package.json of modules

info showing dependencies for 2 modules

- @oncojs/react-survivalplot (0.3.1) [3 dependencies]
└─ @oncojs/survivalplot lodash react

- @oncojs/survivalplot (0.3.3) [2 dependencies]
└─ d3 lodash

✨  Done in 0.77s.
```

I moved cmds into `package.json` so run `yarn styles:build` first and then `yarn start`. Also I added eslint but didn't fix any of the errors.

### CODE REVIEW

**Comment by shanewilson** [comment]
@Jephuff @cheapsteak

**Comment by cheapsteak** [comment]
Is the node_modules folder supposed to be checked in?

**Comment by cheapsteak** [comment]
Can it be named anything besides `node_modules`?

**Comment by shanewilson** [comment]
`modules/node_modules` yes so node can do package resolution without hacks

**Comment by shanewilson** [comment]
you can set 
```
package.json
{
  ...
  "knit": {
    "needle": {
      "paths": {
        "modulesStub": "whatever" 
      } 
    }
  }
}
```

to completely over-ride that if you want to figure out package resolution your self though

**Comment by shanewilson** [comment]
```
> npm install
...
65.26s
```

```
❯ yarn
yarn install v0.17.9
✨  Done in 12.22s.
```

**Comment by shanewilson** [comment]
https://github.com/boennemann/alle

**Comment by cheapsteak** [comment]
I would imagine using node_modules wouldn't play well with quite a few default configs that ignore node_modules

e.g. vscode has in the editor:

```js

  "files.watcherExclude": {
    "**/.git/objects/**": true,
    "**/node_modules/**": true
  },

// ...
  "search.exclude": {
    "**/node_modules": true,
    "**/bower_components": true
  },
```

Perhaps we could use [linklocal](https://www.npmjs.com/package/linklocal) in the postinstall?

**Comment by shanewilson** [comment]
that is really an issue with those tools though - using a heavy handed approach to ignore instead of top level ignore which they should be doing. I get that this is the world we have to develop in, but things like linklocal are really just hacks and work arounds to what `node_modules` does by default.

You are certainly right that by default many configs do this wrong - even the default github `.gitignore` for Node ignores `node_modules` instead of `/node_modules`

**Comment by shanewilson** [comment]
`knit` doesn't care though - since it doesn't execute the code and just does AST walking

**Comment by cheapsteak** [comment]
Reminds me of that Kierkegaard quote about truth always resting with the minority
I usually try to go with the flow, but far be it from me to hinder anyone fighting the good fight ;)

**Comment by shanewilson** [comment]
@cheapsteak I'm hoping we won't be alone for long though:

https://gist.github.com/nolanlawson/457cdb309c9ec5b39f0d420266a9faa4
https://github.com/facebookincubator/create-react-app/pull/1081

**Pull request merged**
